"""empty message

Revision ID: 0473de85caaf
Revises: 2eb746baf8d0
Create Date: 2018-04-19 15:35:52.558984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0473de85caaf'
down_revision = '2eb746baf8d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('outline', sa.String(length=180), nullable=True))
    op.create_index(op.f('ix_posts_outline'), 'posts', ['outline'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_outline'), table_name='posts')
    op.drop_column('posts', 'outline')
    # ### end Alembic commands ###
