"""empty message

Revision ID: 18818f090287
Revises: 0473de85caaf
Create Date: 2018-04-21 21:48:50.867164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18818f090287'
down_revision = '0473de85caaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    # ### end Alembic commands ###
