"""empty message

Revision ID: 420bd47a158a
Revises: 78377defb055
Create Date: 2018-04-26 11:08:32.550002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '420bd47a158a'
down_revision = '78377defb055'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registrations',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registrations')
    # ### end Alembic commands ###
