"""empty message

Revision ID: 615a8722b9b9
Revises: 420bd47a158a
Create Date: 2018-04-26 13:38:18.604259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '615a8722b9b9'
down_revision = '420bd47a158a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('like', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'like')
    # ### end Alembic commands ###
