"""empty message

Revision ID: 78377defb055
Revises: ef0f70440354
Create Date: 2018-04-24 18:46:57.251393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78377defb055'
down_revision = 'ef0f70440354'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('praise', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_posts_praise'), 'posts', ['praise'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_praise'), table_name='posts')
    op.drop_column('posts', 'praise')
    # ### end Alembic commands ###
