"""empty message

Revision ID: 804b55d59071
Revises: 615a8722b9b9
Create Date: 2018-04-26 13:45:45.128506

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '804b55d59071'
down_revision = '615a8722b9b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('likes', sa.Integer(), nullable=True))
    op.drop_column('users', 'like')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('like', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('users', 'likes')
    # ### end Alembic commands ###
