"""empty message

Revision ID: ef0f70440354
Revises: 4f86a9abacd6
Create Date: 2018-04-24 14:35:34.272662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef0f70440354'
down_revision = '4f86a9abacd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('recommend', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'recommend')
    # ### end Alembic commands ###
